// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnpryvjhciddzngbmjuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJucHJ5dmpoY2lkZHpuZ2JtanV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMDMwMDMsImV4cCI6MjA2MTg3OTAwM30.6jvYGLjBjHgtpE-WZ95kMdz4k135n3N2Btu1SbkOovs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);